site_name: StashDB Guidelines
site_url: https://guidelines.stashdb.org
site_description: A list of guidelines and suggestions for StashDB.org contributors, approved by the community.

repo_name: stashapp/StashDB-Docs
repo_url: https://github.com/stashapp/StashDB-Docs
edit_uri: edit/main/docs/

copyright: "Approved by the community driving <a href=\"https://stashdb.org\">StashDB.org</a>"

nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
    - Accessing StashDB: getting-started/accessing-stashdb.md
    - Using StashDB: getting-started/using-stashdb.md
    - Editing StashDB: getting-started/editing-stashdb.md
  - Guides: 
    - guides/index.md
    - Accessing Stash-Boxes: guides/accessing-stash-boxes.md
    - Guideline Proposals: guides/guideline-proposals.md
    - Joining Discourse and Discord: guides/joining-discourse-and-discord.md
    - Submitting Drafts from Stash: guides/submitting-drafts.md
  - FAQ: 
    - faq/index.md
  - Performers: 
    - performers/index.md
    - Generic Actions:
      - Create: performers/generic-actions/create.md
      - Merge: performers/generic-actions/merge.md
      - Destroy: performers/generic-actions/destroy.md
    - Personal Information:
      - Name: performers/personal-information/name.md
      - Disambiguation: performers/personal-information/disambiguation.md
      - Aliases: performers/personal-information/aliases.md
      - Gender: performers/personal-information/gender.md
      - Birthdate: performers/personal-information/birthdate.md
      - Deathdate: performers/personal-information/deathdate.md
      - Eye Color: performers/personal-information/eye-color.md
      - Hair Color: performers/personal-information/hair-color.md
      - Height: performers/personal-information/height.md
      - Breast Type: performers/personal-information/breast-type.md
      - Measurements: performers/personal-information/measurements.md
      - Nationality: performers/personal-information/nationality.md
      - Ethnicity: performers/personal-information/ethnicity.md
      - Career Start & End: performers/personal-information/career-start-end.md
    - Tattoos & Piercings: performers/tattoos-piercings.md
    - Links: performers/links.md
    - Images: performers/images.md
  - Scenes: 
    - scenes/index.md
    - Generic Actions:
      - Create: scenes/generic-actions/create.md
      - Destroy: scenes/generic-actions/destroy.md
    - Details: 
      - Title: scenes/details/title.md
      - Date: scenes/details/date.md
      - Duration: scenes/details/duration.md
      - Performers: scenes/details/performers.md
      - Studio: scenes/details/studio.md
      - Studio Code: scenes/details/studio-code.md
      - Details: scenes/details/details.md
      - Director: scenes/details/director.md
      - Production Date: scenes/details/production-date.md
      - Tags: scenes/details/tags.md
    - Links: scenes/links.md
    - Images: scenes/images.md
  - Studios: 
    - studios/index.md
    - Generic Actions:
      - Create: studios/generic-actions/create.md
      - Destroy: studios/generic-actions/destroy.md
    - Details: 
      - Name: studios/details/name.md
      - Aliases: studios/details/aliases.md
      - Network: studios/details/network.md
    - Links: studios/links.md
    - Images: studios/images.md
  - Tags: 
    - tags/index.md
    - Generic Actions:
      - Create: tags/generic-actions/create.md
      - Merge: tags/generic-actions/merge.md
      - Destroy: tags/generic-actions/destroy.md
    - Details: 
      - Name: tags/details/name.md
      - Description: tags/details/description.md
      - Aliases: tags/details/aliases.md
      - Category: tags/details/category.md
  - Edits: 
    - edits/index.md
  - Moderation: 
    - moderation/index.md
    - Enforcement: moderation/enforcement.md
  - Changelog: changelog.md
  - StashDB.org: https://stashdb.org/


draft_docs: |
  faq_getting-started/search.md
  faq_getting-started/user.md
  performers/delete.md
  scenes/delete.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - navigation.footer    
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - tables
  - pymdownx.snippets:
      auto_append:
        - includes/invite-code.md
      url_download: true
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.saneheaders
  - pymdownx.keys